name: therapify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  awesome_bottom_bar: ^1.2.4
  card_swiper: ^3.0.1
  circular_seek_bar: ^1.1.1
  cloud_firestore: ^5.6.2
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dot_navigation_bar: ^1.0.2
  dotted_border: ^2.1.0
  dotted_line: ^3.2.3
  dropdown_button2: ^2.3.9
  file_picker: ^8.3.2
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_storage: ^12.4.1
  floating: ^6.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  flutter_ringtone_player: ^4.0.0+4
  flutter_screenutil: ^5.9.0
  flutter_xlider: ^3.5.0
  fluttertoast: ^8.2.5
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: 6.1.0
  google_maps_flutter: ^2.9.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  ionicons: ^0.2.2
  lottie: ^3.1.3
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pinput: ^3.0.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  readmore: ^3.0.0
  rename_app: ^1.3.2
  share_plus: ^10.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  win32: ^5.8.0
  zego_uikit_prebuilt_call: ^4.16.22

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/doctor/
    - assets/images/department/

  fonts:
    - family: Enriqueta
      fonts:
        - asset: assets/fonts/Enriqueta-Regular.ttf
          weight: 400
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
